kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
{{- if hasKey $ "name" }}
name: {{ $.name }}
{{- end }}
nodes:
- role: control-plane
  {{- if hasKey $ "image" }}
  image: {{ $.image }}
  {{- end }}
{{- range $.workers }}
- role: worker
  {{- if hasKey $ "image" }}
  image: {{ $.image }}
  {{- end }}
  extraMounts:
    {{- range $npu := untilStep $worker (add $worker 1) 1 }}
    - hostPath: /dev/null
      containerPath: /var/run/furiosa-container-devices/{{ $npu }}
    {{- end }}
{{- end }}
